### ISSUE TITLE
Windows flaky test

### ISSUE THREAD

**Issue by Irtazaraza** [typedb/typedb-studio#130]
## Description

unit tests fail due to flaky test

issue persists even after PR #95 

## Environment

1. OS (where Grakn server runs): Windows instance in gcp
2. Grakn version (and platform): Grakn Core 1.5

## Reproducible Steps

N/A

## Expected Output

PASS

## Actual Output

FAIL 

 ```jest: failed to cache transform results in: C:/Users/circleci/AppData/Local/Temp/jest/jest-transform-cache-2af1f1cd6f842a951c23edf0f89257db-9a9740a15a86d43e50d470de08968b86/84/getters_848e7465bdb68294fbe4de8b779a51a8.map
    Failure message: EBADF: bad file descriptor, close
```

## Additional information

https://circleci.com/gh/graknlabs/workbase/1331?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

https://circleci.com/gh/graknlabs/workbase/1210?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

https://circleci.com/gh/graknlabs/workbase/1203?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

https://circleci.com/gh/graknlabs/workbase/1081?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by haikalpribadi** [comment]
I've moved this issue from milestone `1.2.0` to `1.2.1`, @Irtazaraza as it was created after `1.2.0` was already released. Which means it will only go out for the `1.2.1` release.
