### ISSUE TITLE
Add and remember connection configurations

### ISSUE THREAD

**Issue by alexjpwalker** [typedb/typedb-studio#428]
Once https://github.com/vaticle/typedb-workbase/issues/413 (Connect to TypeDB) is implemented, we'll have a form allowing users to connect to a database server.

But it would suck if they had to type the server address each time.

When loading the Connection dialog:

- [ ] if `appData.typeDBServerAddresses` is not set, set it to `127.0.0.1:1729`.
- [ ] pre-populate the server address list with values from `appData.typeDBServerAddresses`.

Also:

- [ ] On any attempt to connect a server address in the Connection form, prepend the server address to `appData.typeDBServerAddresses`, which should be a comma-separated list of addresses.
- [ ] If the address is already in the list, move it to the front of the list.
- [ ] If the resulting list size exceeds 10, pop from the end of the list until it has size 10.
- [ ] On modifying the list, update the actual server address selector element to match.

**Comment by jamesreprise** [comment]
We'd like for users to have a seamless experience when reconnecting to a server they've provided credentials for in the past. In particular, switching between cluster instances is unwieldy given the amount of information you have to provide.

**Comment by jamesreprise** [comment]
We're shelving this until the next milestone.
